version: '3.10'

services:
  api:
    container_name: api
    build:
      context: ./back-end/InvoiceSystemAPI/InvoiceSystemAPI
      dockerfile: Dockerfile
    ports:
      - "7110:7110"
      - "5177:80"

  front:
    container_name: front
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/app
      - /app/node_modules