on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: |
          cd back-end/InvoiceSystemAPI
          dotnet restore
      - name: Build
        run: |
          cd back-end/InvoiceSystemAPI
          dotnet build --no-restore
      - name: Test
        run: |
          cd back-end/InvoiceSystemAPI
          dotnet test
